"""Package what a fresh install needs to trade: the deployed selector and fly, the connectome they run on, and the
database rows that admit them -- written for the container's layout (``/app/data``).

Run on the machine that trained them (a master checkout with its database), after a passed replay:

    .venv/bin/python tools/make_seed.py --out dist

Outputs, under ``--out``:
  models/policies/<fly>.pt, models/selectors/<selector>.joblib, models/connectome/{current.txt, <npz>, scale.json}
  seed/seed.sql  -- brain_snapshots rows (ids kept, so the pin still points at its selector), ui_settings: the replay
                    verdict the fly session requires, the selector pin, and autostart for the two trading workers.
                    Idempotent: every statement is ON CONFLICT DO NOTHING, so a running install is never overwritten.

The distribution branch copies these into its tracked ``models/`` and ``seed/`` -- that is the whole "refresh" step.
"""
from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))     # runnable as a script from any directory

from fly_trader import config  # noqa: E402
from fly_trader.agent.selector_session import pinned_snapshot
from fly_trader.db.connection import transaction
from fly_trader.train import fly_selector, selector

CONTAINER_DATA = "/app/data"
AUTOSTART = {"pumpstream": True, "runner": True, "train": False, "replay": False, "discover": False}


def _lit(v) -> str:
    """A SQL literal: strings quoted, JSON for dicts, NULL for None."""
    if v is None:
        return "NULL"
    if isinstance(v, dict):
        v = json.dumps(v, default=str)
    return "'" + str(v).replace("'", "''") + "'"


def main(out: Path) -> None:
    with transaction() as conn:
        fly = fly_selector.latest_deployable(conn)
        if not fly:
            raise SystemExit("no deployable fly: bootstrap one first (fly-trader train-fly-selector) and run the replay")
        pin = pinned_snapshot()
        sel_id = pin if pin is not None else (selector.latest_current(conn) or {}).get("id")
        if sel_id is None:
            raise SystemExit("no deployed selector: pin one (ui_settings.pinned_selector_snapshot) or train one that qualifies")
        rows = {r["id"]: dict(r) for r in conn.execute("SELECT * FROM brain_snapshots WHERE id = ANY(%s)", ([int(fly["id"]), int(sel_id)],)).fetchall()}
        verdict = conn.execute("SELECT value FROM ui_settings WHERE key = 'fly_replay'").fetchone()
    if not verdict:
        raise SystemExit("no replay verdict stored: the fly session refuses to trade without one (fly-trader fly-replay)")
    v = verdict["value"] if isinstance(verdict["value"], dict) else json.loads(verdict["value"])
    if not v.get("passed") or v.get("data") != fly_selector.FLY_VERSION:
        raise SystemExit("the stored replay verdict did not pass on the current definitions: run fly-trader fly-replay again")

    models = out / "models"; (models / "policies").mkdir(parents=True, exist_ok=True); (models / "selectors").mkdir(exist_ok=True); (models / "connectome").mkdir(exist_ok=True)
    stmts = ["-- generated by tools/make_seed.py: the rows a fresh install needs to trade. Safe to re-run: nothing here overwrites."]
    for sid, r in sorted(rows.items()):
        src = Path(r["path"]); sub = "policies" if r["kind"] == "fly_selector" else "selectors"
        shutil.copy2(src, models / sub / src.name)
        r["path"] = f"{CONTAINER_DATA}/brain/{sub}/{src.name}"
        cols = ("id", "ts", "run_id", "beat_id", "path", "sha256", "kind", "promoted_at", "promoted_by", "note")
        stmts.append(f"INSERT INTO brain_snapshots ({', '.join(cols)}) VALUES ({', '.join(_lit(r[c]) for c in cols)}) ON CONFLICT (id) DO NOTHING;")
    stmts.append("SELECT setval('brain_snapshots_id_seq', GREATEST((SELECT max(id) FROM brain_snapshots), 1));")
    settings = {"fly_replay": v, "autostart": AUTOSTART,
                "pinned_selector_snapshot": {"id": int(sel_id), "why": "shipped with the distribution: the selector this fly was taught by", "pinned_at": str(fly["meta"].get("S", ""))[:10]}}
    for k, val in settings.items():
        stmts.append(f"INSERT INTO ui_settings (key, value) VALUES ({_lit(k)}, {_lit(val)}::jsonb) ON CONFLICT (key) DO NOTHING;")
    (out / "seed").mkdir(exist_ok=True)
    (out / "seed" / "seed.sql").write_text("\n".join(stmts) + "\n")

    cdir = config.BRAIN_DIR / "connectome"; current = (cdir / "current.txt").read_text().strip()
    for name in ("current.txt", "scale.json", current):
        shutil.copy2(cdir / name, models / "connectome" / name)
    print(f"seed written to {out}/: fly #{fly['id']} ({Path(rows[int(fly['id'])]['path']).name}), selector #{sel_id}, connectome {current}")
    print(f"  fly taught by: {fly['meta'].get('teacher')}")
    print(f"  replay verdict: {v.get('reason')}")


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--out", type=Path, default=Path("dist"), help="output directory (default: dist/)")
    main(ap.parse_args().out)
